[local]
localhost

[mongodb]
mongodb.testzpaaws.bond

[redis]
redis.testzpaaws.bond

[mysql]
mysql.testzpaaws.bond

[rabbitmq]
rabbitmq.testzpaaws.bond

[catalogue]
catalogue.testzpaaws.bond

[user]
user.testzpaaws.bond

[cart]
cart.testzpaaws.bond

[shipping]
shipping.testzpaaws.bond

[payment]
payment.testzpaaws.bond

[frontend]
frontend.testzpaaws.bond