ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb.testzpaaws.bond
REDIS_HOST: redis.testzpaaws.bond
MYSQL_HOST: mysql.testzpaaws.bond 
RABBITMQ_HOST: rabbitmq.testzpaaws.bond 
CATALOGUE_HOST: catalogue.testzpaaws.bond
USER_HOST: user.testzpaaws.bond
CART_HOST: cart.testzpaaws.bond
SHIPPING_HOST: shipping.testzpaaws.bond
PAYMENT_HOST: payment.testzpaaws.bond