---
- name: ping module
  hosts: localhost
  become: true

  tasks:

    - name: ping
      ping:
      register: ping_output

    - name: Save full output
      copy:
        content: "{{ ping_output | to_nice_json }}"
        dest: /home/ec2-user/Ansible/Basic/full_output.json

    - name: print output
      debug:
        var: ping_output